language: node_js
node_js:
- '10'
- '8'
- '6'
install:
- npm install
- npm install -g nyc eslint
script:
- npm run test_coverage
- npm run lint
after_success:
- npm install -g codecov
- codecov
deploy:
  provider: npm
  email: kei.itof@gmail.com
  api_key:
    secure: YtwXohqSPRCeKBqzzUmb0slRYkB/rBSSiveeh+nzxIlxxhMpMqUBLhUwmgSRUdw/lb4KIwwJnp5Y/RWinVcycLY1uolhi3NHKMbxlOga/P4BwQp/NDMZ/AzTTXxw1XIObXW2yQJgpK6BWIfzIasGj3+BjdfurwqPc5Z1AS+39tkOJWjRn+x+vmexJqfWNp5kOKZ0lEho42SD7uIpXqolH0oEOkuW1IL7QbeGqDoqJXGwLp7N3VwOQASmZwIRqXp6QqXSopFVfBi9hcTApQ8Y4w0CfZQEgNyPiWXddHCWQnv4E/lwDIpcQszivK8cbti++Yecz34f8+m6H8f3/V2nUjQYyGQsO1mFK1sEBL2HDkBAeVD34GK5hYRzfZtfHT3P9tuFSCQem7Ncl1ovYXGGydA2taiGd/xU+tBapppJv4Bd6LokGu8LF+lxYr8/KTsy3MA3b98VAwOPt+6SH8qebVK+5NVZdMg7ALINtPUQQX21al091vs56i3rWUfgReqWXtM2s6NTBxgPDDE+spA9ahLqN3kp2EsYFzNYfBxWDwR0FJ2HBfOHhyXnRLUGHDWOU6TsP+09oRMHwn6FGE2z+Blx5m6PM6ywTpRtffBDv+Z99TySnj/vdPQhwItkfgBHD4lTmbLOattxWWCHnSi6YShiG9J0HTCFAs+V0i9FPv0=
  on:
    tags: true
    repo: kei-ito/nunjucks-watch
