language: node_js
node_js:
- '7'
notifications:
  slack:
    secure: VBhWZgOYuCRb7Fxi84G2nAeMXaump9zcNaXi2OJ9AuI7yA2AAcAAyhBjJWNBbDw41m/iFTLKc7PxCJgawQ5M88At+mKGq9JvcyHYgqoww7maS8XIx41NT8HfciVmSa+qtQVddTmqskTZttEse6EblkUQIX+pvJX7F8wuafq+cVMa/v5zxfyV4VuRm0G1Q4Z7pVVTI2s8nY4xvwMWQKWQipiuAwFida9p7hwnYRAjq8P0SBkHsFu1OnECVbnxwT1caA9ykHU1LX4zAPyfpGzq69yZYA9CSiAmBE9jvXVN9ooLanlpwdkX6cj7NpPPWt/bMplXCE7Tdxh3qbYJGvtMQoFqyX9CO/EqD6sahaj+4sodpGn2U/amfOBu6QEp4RjsaveC04m4sMllMoxosuaXHxAkeNLknwLfEodm6xqk4SvQPirh3ppcuy6FZ4syAp9cHLGMgRplsWdbQYdIx/SVhNepvopSNWy67Ci4ApdlZsoXwtsyj2QPKLEgkFMerLik+R31y9/Xk/XpNS4Lxgwb5AU/4AHEaL2VxGTvewmX+vu526u7ck1+b7oKLQCnCFYSF8AHHTTJmPCjLI9yoEWPcx80S0U7cMCycfUMb6uTHsaqoB3ZMeh2kNl9zm9mQZpTM+aerdjOxs+kQpMOxc1yfQqT6fdZkfDJH5iDqsem+b8=
addons:
  code_climate: cc9aee6be861c3df70e1240a0dea8baaf9d4459b234d6ecfd7c94cb4e63d6bec
script: npm run test_coverage
after_success:
- npm install -g codeclimate-test-reporter
- CODECLIMATE_REPO_TOKEN=cc9aee6be861c3df70e1240a0dea8baaf9d4459b234d6ecfd7c94cb4e63d6bec
  codeclimate-test-reporter < ./coverage/lcov.info
deploy:
  provider: npm
  email: kei.itof@gmail.com
  api_key:
    secure: Lvo8QzKQGxvE8TQBV98ZIl2t8p5R2WGVZhLco8IMaNFsOkuYWgzSYiJxg0IZSN7+AaHIithnRzet00GsOzXWYj4M68JbHSr4KiB7X2EuHyRLYv1uQWTXgTKX/9vvfrgjZk6prj3YBxG6mYV2NvsJWy1VXvqzHxPHKmNTs7WvG7sHBTW/Loa3xSoxqP4+GYLfk8CTJ8OsKYZdf+WvHr8jjPpkyUyfvhhTWZrGXz7hYGogosJjh4a7GHL1OpIwNf3qmLRso3sA+tKOjbtAkJSdCi1oRSLGwyxWT7TSxRVUr7pBSpS9yNTrGaoJB/S1m3C6iYtImq6m1iZjEDdLv7Yb1yClrdYMX5EPKo7pyRS5QhggSxTeavHn2dZoynJfRZciGa46RuW+ujGGOUOjXXYA9Sonk3+I499PwW0fOCAiabzucwAxGTmG+xfTYE4QWBzZ0svULdBUsRwQ0C7xSMpVsJe10M364PRLRKTM+5xsscQshCvyvLPF1bB+aFxtHtU3pnss6OdHQ4DBscCqtyApwnFDFZKF9aHqjY6ZlaMayCgUBTHQUutm+naVb87ozNnwqU9boDvT9KGgnFH2J60FYRiPMFvKe5OHC1cisueWJGdqfDmGAnwunyJBvfPtyD4VlME9LNu37kONllksWEiPnHTatDwLt++Gu9kUYNn2ROA=
  on:
    tags: true
    branch: master
    repo: kei-ito/nunjucks-watch
